# Generated by Django 5.2.7 on 2026-04-22 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_clothingproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
